import type {
  PortfolioIntelligenceReport,
  ExportFormat,
  PortfolioRecommendation,
  PortfolioInsight,
  PortfolioHealth,
  AssetDistribution,
  ActivitySummary,
  PortfolioTrend,
  PortfolioMetric,
  TokenDistribution,
} from "../types";

function formatDate(ts: number): string {
  return new Date(ts).toISOString().slice(0, 19).replace("T", " ");
}

function buildMarkdownHeader(report: PortfolioIntelligenceReport): string {
  return [
    `# Portfolio Intelligence Report`,
    "",
    `**Address:** \`${report.address}\``,
    `**Generated:** ${formatDate(report.generatedAt)}`,
    `**Health Score:** ${report.health.score}/100 (${report.health.level})`,
    "",
    "---",
    "",
  ].join("\n");
}

function buildHealthSection(health: PortfolioHealth): string {
  return [
    "## Portfolio Health",
    "",
    `**Overall Score:** ${health.score}/100`,
    `**Level:** ${health.level.toUpperCase()}`,
    `**Diversification:** ${health.diversificationScore}/100`,
    `**Activity:** ${health.activityScore}/100`,
    `**Risk:** ${health.riskScore}/100`,
    "",
    health.summary,
    "",
    "### Factors",
    "",
    ...health.factors.map((f) => `- **${f.label}:** ${f.value}/${f.max} (${f.impact})`),
    "",
  ].join("\n");
}

function buildMetricsSection(metrics: PortfolioMetric[]): string {
  if (metrics.length === 0) return "";
  return [
    "## Key Metrics",
    "",
    ...metrics.map((m) => `- **${m.label}:** ${m.value}${m.unit ? ` ${m.unit}` : ""}`),
    "",
  ].join("\n");
}

function buildDistributionSection(distribution: AssetDistribution[]): string {
  if (distribution.length === 0) return "";
  return [
    "## Asset Distribution",
    "",
    ...distribution.map((d) => `- **${d.label}:** ${d.count} items (${d.percentage}%)`),
    "",
  ].join("\n");
}

function buildTokenSection(tokens: TokenDistribution[]): string {
  if (tokens.length === 0) return "";
  return [
    "## Token Holdings",
    "",
    ...tokens.slice(0, 10).map((t) => `- **${t.symbol || t.name}:** ${t.balance} (${t.percentage}%) [${t.standard}]`),
    "",
  ].join("\n");
}

function buildActivitySection(activity: ActivitySummary): string {
  return [
    "## Activity Summary",
    "",
    `- **Total Transactions:** ${activity.totalTransactions}`,
    `- **Active Days:** ${activity.activeDays}`,
    `- **Avg Daily Transactions:** ${activity.avgDailyTransactions}`,
    `- **Unique Contracts:** ${activity.uniqueContracts}`,
    `- **Unique Tokens:** ${activity.uniqueTokens}`,
    `- **Inbound Transfers:** ${activity.inboundTransfers}`,
    `- **Outbound Transfers:** ${activity.outboundTransfers}`,
    "",
  ].join("\n");
}

function buildTrendsSection(trends: PortfolioTrend[]): string {
  if (trends.length === 0) return "";
  return [
    "## Trends",
    "",
    ...trends.flatMap((t) => [
      `### ${t.timeframe.charAt(0).toUpperCase() + t.timeframe.slice(1)}`,
      ...t.dataPoints.map((dp) => `  - ${dp.label}: ${dp.transactions} tx, ${dp.gasUsed} gas`),
      `- Direction: ${t.direction}`,
      `- Transfer Frequency: ${t.transferFrequency}`,
      `- Gas Spending Trend: ${t.gasSpendingTrend}`,
      `- New Tokens: ${t.newTokensReceived}`,
      `- New NFTs: ${t.newNFTsReceived}`,
      "",
    ]),
  ].join("\n");
}

function buildRecommendationsSection(recs: PortfolioRecommendation[]): string {
  if (recs.length === 0) return "## Recommendations\n\nNo recommendations at this time.\n";
  return [
    "## Recommendations",
    "",
    ...recs.map(
      (r) =>
        `### [${r.priority.toUpperCase()}] ${r.title}\n\n` +
        `${r.description}` +
        (r.action ? `\n\n**Action:** ${r.action}` : ""),
    ),
    "",
  ].join("\n");
}

function buildInsightsSection(insights: PortfolioInsight[]): string {
  if (insights.length === 0) return "## Insights\n\nNo insights generated.\n";
  return [
    "## Insights",
    "",
    ...insights.map(
      (i) =>
        `### [${i.severity.toUpperCase()}] ${i.title}\n\n${i.description}`,
    ),
    "",
  ].join("\n");
}

export function exportReportMarkdown(report: PortfolioIntelligenceReport): string {
  return [
    buildMarkdownHeader(report),
    buildHealthSection(report.health),
    buildMetricsSection(report.metrics),
    buildDistributionSection(report.assetDistribution),
    buildTokenSection(report.tokenDistribution),
    buildActivitySection(report.activitySummary),
    buildTrendsSection(report.trends),
    buildInsightsSection(report.insights),
    buildRecommendationsSection(report.recommendations),
    "---",
    "",
    `*Generated by BlockMind Portfolio Intelligence*`,
  ].join("\n");
}

export function exportReportJSON(report: PortfolioIntelligenceReport): string {
  return JSON.stringify(report, null, 2);
}

function buildCSVRow(values: (string | number)[]): string {
  return values
    .map((v) => {
      const s = String(v);
      if (s.includes(",") || s.includes('"') || s.includes("\n")) {
        return `"${s.replace(/"/g, '""')}"`;
      }
      return s;
    })
    .join(",");
}

export function exportReportCSV(report: PortfolioIntelligenceReport): string {
  const lines: string[] = [];

  lines.push(buildCSVRow(["Section", "Key", "Value"]));
  lines.push("");

  lines.push(buildCSVRow(["Health", "Score", report.health.score]));
  lines.push(buildCSVRow(["Health", "Level", report.health.level]));
  lines.push(buildCSVRow(["Health", "Diversification", report.health.diversificationScore]));
  lines.push(buildCSVRow(["Health", "Activity", report.health.activityScore]));
  lines.push(buildCSVRow(["Health", "Risk", report.health.riskScore]));
  lines.push("");

  for (const m of report.metrics) {
    lines.push(buildCSVRow(["Metric", m.label, m.value]));
  }
  lines.push("");

  for (const d of report.assetDistribution) {
    lines.push(buildCSVRow(["Distribution", d.label, `${d.count} (${d.percentage}%)`]));
  }
  lines.push("");

  lines.push(buildCSVRow(["Activity", "Total Transactions", report.activitySummary.totalTransactions]));
  lines.push(buildCSVRow(["Activity", "Active Days", report.activitySummary.activeDays]));
  lines.push(buildCSVRow(["Activity", "Unique Contracts", report.activitySummary.uniqueContracts]));
  lines.push(buildCSVRow(["Activity", "Unique Tokens", report.activitySummary.uniqueTokens]));
  lines.push("");

  for (const r of report.recommendations) {
    lines.push(buildCSVRow(["Recommendation", r.title, `[${r.priority}] ${r.description}`]));
  }

  return lines.join("\n");
}

export function exportPortfolioReport(
  report: PortfolioIntelligenceReport,
  format: ExportFormat,
): { content: string; mimeType: string; filename: string } {
  const addressShort = report.address.slice(0, 10);
  const dateStr = new Date(report.generatedAt).toISOString().slice(0, 10);

  switch (format) {
    case "markdown":
      return {
        content: exportReportMarkdown(report),
        mimeType: "text/markdown",
        filename: `portfolio-${addressShort}-${dateStr}.md`,
      };
    case "json":
      return {
        content: exportReportJSON(report),
        mimeType: "application/json",
        filename: `portfolio-${addressShort}-${dateStr}.json`,
      };
    case "csv":
      return {
        content: exportReportCSV(report),
        mimeType: "text/csv",
        filename: `portfolio-${addressShort}-${dateStr}.csv`,
      };
  }
}
